[build]
  command = "npm run generate"
  publish = ".output/public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = ".output/public" 