[build]
  command = "NITRO_PRESET=netlify npm run build"
  publish = ".output/public"
  functions = ".output/server"

[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NITRO_PRESET = "netlify"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = ".output/public"
  autoLaunch = true

[functions]
  directory = ".output/server"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"