[build]
  command = "nuxt build"
  publish = ".output/public"
  edge_functions = "edge-functions"

[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NITRO_PRESET = "netlify"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888