[build]
  command = "npm run build"
  publish = ".output/public"
  functions = ".output/server"

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NITRO_PRESET = "netlify"

[functions]
  node_bundler = "esbuild"
  included_files = ["server/chunks/**", "server/node_modules/**"]