// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/25/2024, 1:34:04 PM
const configMerger = require("C:/Users/bh1/.cursor-tutor-1/leyef-hub/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/bh1/.cursor-tutor-1/leyef-hub/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/plugins/**/*.{js,ts,mjs}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/composables/**/*.{js,ts,mjs}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/utils/**/*.{js,ts,mjs}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bh1/.cursor-tutor-1/leyef-hub/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})()
